/**
 * Banco de dados SQL das entidades do site Sinteemar
 * @author Luiz Joaquim Aderaldo Amichi <luizamichi@luizamichi.com.br>
 * @copyright 2021 Luiz Joaquim Aderaldo Amichi
 */

CREATE DATABASE IF NOT EXISTS SINTEEMAR;
ALTER DATABASE SINTEEMAR CHARACTER SET 'utf8' COLLATE 'utf8_general_ci';
USE SINTEEMAR;
SET COLLATION_CONNECTION = 'utf8_general_ci';
SET SQL_MODE = 'NO_AUTO_VALUE_ON_ZERO';
SET time_zone = '+03:00';

CREATE TABLE IF NOT EXISTS PERMISSAO (
	`ID` INT NOT NULL AUTO_INCREMENT, -- CHAVE ÚNICA ATRIBUÍDA À PERMISSÃO
	`BANNER` TINYINT(1) NOT NULL DEFAULT 0, -- PERMISSÃO PARA REALIZAR LEITURA, ESCRITA, ALTERAÇÃO E REMOÇÃO NA TABELA DO BANNER
	`BOLETIM` TINYINT(1) NOT NULL DEFAULT 0, -- PERMISSÃO PARA REALIZAR LEITURA, ESCRITA, ALTERAÇÃO E REMOÇÃO NA TABELA DE BOLETIM
	`CONVENCAO` TINYINT(1) NOT NULL DEFAULT 0, -- PERMISSÃO PARA REALIZAR LEITURA, ESCRITA, ALTERAÇÃO E REMOÇÃO NA TABELA DE CONVENÇÃO
	`CONVENIO` TINYINT(1) NOT NULL DEFAULT 0, -- PERMISSÃO PARA REALIZAR LEITURA, ESCRITA, ALTERAÇÃO E REMOÇÃO NA TABELA DE CONVÊNIO
	`DIRETORIO` TINYINT(1) NOT NULL DEFAULT 0, -- PERMISSÃO PARA REALIZAR LEITURA DE DIRETÓRIO
	`EDITAL` TINYINT(1) NOT NULL DEFAULT 0, -- PERMISSÃO PARA REALIZAR LEITURA, ESCRITA, ALTERAÇÃO E REMOÇÃO NA TABELA DE EDITAL
	`EVENTO` TINYINT(1) NOT NULL DEFAULT 0, -- PERMISSÃO PARA REALIZAR LEITURA, ESCRITA, ALTERAÇÃO E REMOÇÃO NA TABELA DE EVENTO
	`FINANCA` TINYINT(1) NOT NULL DEFAULT 0, -- PERMISSÃO PARA REALIZAR LEITURA, ESCRITA, ALTERAÇÃO E REMOÇÃO NA TABELA DO FINANÇA
	`JORNAL` TINYINT(1) NOT NULL DEFAULT 0, -- PERMISSÃO PARA REALIZAR LEITURA, ESCRITA, ALTERAÇÃO E REMOÇÃO NA TABELA DE JORNAL
	`JURIDICO` TINYINT(1) NOT NULL DEFAULT 0, -- PERMISSÃO PARA REALIZAR LEITURA, ESCRITA, ALTERAÇÃO E REMOÇÃO NA TABELA DO JURÍDICA
	`NOTICIA` TINYINT(1) NOT NULL DEFAULT 0, -- PERMISSÃO PARA REALIZAR LEITURA, ESCRITA, ALTERAÇÃO E REMOÇÃO NA TABELA DE NOTÍCIA
	`PODCAST` TINYINT(1) NOT NULL DEFAULT 0, -- PERMISSÃO PARA REALIZAR LEITURA, ESCRITA, ALTERAÇÃO E REMOÇÃO NA TABELA DE PODCAST
	`REGISTRO` TINYINT(1) NOT NULL DEFAULT 0, -- PERMISSÃO PARA REALIZAR LEITURA NA TABELA DE REGISTRO
	`TABELA` TINYINT(1) NOT NULL DEFAULT 0, -- PERMISSÃO PARA REALIZAR LEITURA DE TABELAS
	`USUARIO` TINYINT(1) NOT NULL DEFAULT 0, -- PERMISSÃO PARA REALIZAR LEITURA, ESCRITA, ALTERAÇÃO E REMOÇÃO NA TABELA DE USUÁRIO
	PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE IF NOT EXISTS USUARIO (
	`ID` INT NOT NULL AUTO_INCREMENT, -- CHAVE ÚNICA ATRIBUÍDA AO USUÁRIO
	`NOME` VARCHAR(64) CHARACTER SET utf8 NOT NULL, -- NOME COMPLETO DO USUÁRIO
	`EMAIL` VARCHAR(64) CHARACTER SET utf8 NOT NULL, -- E-MAIL DO USUÁRIO
	`LOGIN` VARCHAR(64) CHARACTER SET utf8 NOT NULL UNIQUE, -- LOGIN DO USUÁRIO
	`SENHA` CHAR(32) CHARACTER SET utf8 NOT NULL, -- SENHA CRIPTOGRAFADA COM MD5
	`PERMISSAO` INT NOT NULL, -- PERMISSÕES PARA LEITURA, ESCRITA, ALTERAÇÃO E REMOÇÃO NAS TABELAS DO SISTEMA
	`STATUS` TINYINT(1) NOT NULL DEFAULT 1, -- INATIVO (0), ATIVO (1)
	PRIMARY KEY (`ID`),
	FOREIGN KEY (`PERMISSAO`) REFERENCES PERMISSAO(`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE IF NOT EXISTS ACESSO (
	`ID` INT NOT NULL AUTO_INCREMENT, -- CHAVE ÚNICA ATRIBUÍDA AO ACESSO
	`IP` VARCHAR(64) NOT NULL, -- ENDEREÇO DO VISITANTE
	`DATA` DATETIME NOT NULL, -- DATA E HORA DO SERVIDOR
	PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE IF NOT EXISTS BANNER (
	`ID` INT NOT NULL AUTO_INCREMENT, -- CHAVE ÚNICA ATRIBUÍDA AO BANNER
	`IMAGEM` VARCHAR(64) CHARACTER SET utf8 NOT NULL, -- ENDEREÇO DA IMAGEM (JPG OU PNG)
	`USUARIO` INT NOT NULL, -- USUÁRIO RESPONSÁVEL POR INSERIR (ALTERAR) O BANNER
	`DATA` DATETIME NOT NULL, -- DATA E HORA DO SERVIDOR
	`STATUS` TINYINT(1) NOT NULL DEFAULT 1, -- INATIVO (0), ATIVO (1)
	PRIMARY KEY (`ID`),
	FOREIGN KEY (`USUARIO`) REFERENCES USUARIO(`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE IF NOT EXISTS BOLETIM (
	`ID` INT NOT NULL AUTO_INCREMENT, -- CHAVE ÚNICA ATRIBUÍDA AO BOLETIM
	`TITULO` VARCHAR(128) CHARACTER SET utf8 NOT NULL, -- TÍTULO DO BOLETIM
	`ARQUIVO` VARCHAR(64) CHARACTER SET utf8 NOT NULL, -- ENDEREÇO DO ARQUIVO PDF
	`IMAGEM` VARCHAR(64) CHARACTER SET utf8 NULL, -- ENDEREÇO DA IMAGEM (JPG OU PNG)
	`USUARIO` INT NOT NULL, -- USUÁRIO RESPONSÁVEL POR INSERIR (ALTERAR) O BOLETIM
	`DATA` DATETIME NOT NULL, -- DATA E HORA DO SERVIDOR
	`STATUS` TINYINT(1) NOT NULL DEFAULT 1, -- INATIVO (0), ATIVO (1)
	PRIMARY KEY (`ID`),
	FOREIGN KEY (`USUARIO`) REFERENCES USUARIO(`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE IF NOT EXISTS CONVENCAO (
	`ID` INT NOT NULL AUTO_INCREMENT, -- CHAVE ÚNICA ATRIBUÍDA À CONVENÇÃO
	`TITULO` VARCHAR(128) CHARACTER SET utf8 NOT NULL, -- DESCRIÇÃO DA CONVENÇÃO
	`ARQUIVO` VARCHAR(64) CHARACTER SET utf8 NOT NULL, -- ENDEREÇO DO ARQUIVO PDF
	`TIPO` TINYINT(1) NOT NULL DEFAULT 1, -- ANTERIOR (0), VIGENTE (1)
	`USUARIO` INT NOT NULL, -- USUÁRIO RESPONSÁVEL POR INSERIR (ALTERAR) A CONVENÇÃO
	`DATA` DATETIME NOT NULL, -- DATA E HORA DO SERVIDOR
	`STATUS` TINYINT(1) NOT NULL DEFAULT 1, -- INATIVO (0), ATIVO (1)
	PRIMARY KEY (`ID`),
	FOREIGN KEY (`USUARIO`) REFERENCES USUARIO(`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE IF NOT EXISTS CONVENIO (
	`ID` INT NOT NULL AUTO_INCREMENT, -- CHAVE ÚNICA ATRIBUÍDA AO CONVÊNIO
	`TITULO` VARCHAR(128) CHARACTER SET utf8 NOT NULL, -- NOME DO CONVÊNIO OU DA EMPRESA
	`DESCRICAO` TEXT CHARACTER SET utf8 NOT NULL, -- DESCRIÇÃO DO CONVÊNIO
	`CIDADE` VARCHAR(64) CHARACTER SET utf8 NOT NULL, -- CIDADE DE ATENDIMENTO DA EMPRESA
	`TELEFONE` VARCHAR(16) CHARACTER SET utf8 NULL, -- DDD + TELEFONE
	`CELULAR` VARCHAR(16) CHARACTER SET utf8 NULL, -- DDD + CELULAR
	`SITE` VARCHAR(64) CHARACTER SET utf8 NULL, -- WEBSITE DA EMPRESA
	`EMAIL` VARCHAR(64) CHARACTER SET utf8 NULL, -- E-MAIL DA EMPRESA
	`IMAGEM` VARCHAR(64) CHARACTER SET utf8 NOT NULL, -- ENDEREÇO DA IMAGEM LOGOTIPO (JPG OU PNG)
	`ARQUIVO` VARCHAR(64) CHARACTER SET utf8 NULL, -- ENDEREÇO DO ARQUIVO PDF COM DETALHES
	`USUARIO` INT NOT NULL, -- USUÁRIO RESPONSÁVEL POR INSERIR (ALTERAR) O CONVÊNIO
	`DATA` DATETIME NOT NULL, -- DATA E HORA DO SERVIDOR
	`STATUS` TINYINT(1) NOT NULL DEFAULT 1, -- INATIVO (0), ATIVO (1)
	PRIMARY KEY (`ID`),
	FOREIGN KEY (`USUARIO`) REFERENCES USUARIO(`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE IF NOT EXISTS EDITAL (
	`ID` INT NOT NULL AUTO_INCREMENT, -- CHAVE ÚNICA ATRIBUÍDA AO EDITAL
	`TITULO` VARCHAR(128) CHARACTER SET utf8 NOT NULL, -- TÍTULO DO EDITAL
	`DESCRICAO` TEXT CHARACTER SET utf8 NULL, -- DESCRIÇÃO DO EDITAL
	`IMAGEM` VARCHAR(64) CHARACTER SET utf8 NOT NULL, -- ENDEREÇO DA IMAGEM (JPG OU PNG)
	`USUARIO` INT NOT NULL, -- USUÁRIO RESPONSÁVEL POR INSERIR (ALTERAR) O EDITAL
	`DATA` DATETIME NOT NULL, -- DATA E HORA DO SERVIDOR
	`STATUS` TINYINT(1) NOT NULL DEFAULT 1, -- INATIVO (0), ATIVO (1)
	PRIMARY KEY (`ID`),
	FOREIGN KEY (`USUARIO`) REFERENCES USUARIO(`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE IF NOT EXISTS EVENTO (
	`ID` INT NOT NULL AUTO_INCREMENT, -- CHAVE ÚNICA ATRIBUÍDA AO EVENTO
	`TITULO` VARCHAR(64) CHARACTER SET utf8 NOT NULL, -- NOME DO EVENTO
	`DESCRICAO` TEXT CHARACTER SET utf8 NULL, -- DESCRIÇÃO DO EVENTO
	`DIRETORIO` VARCHAR(64) CHARACTER SET utf8 NOT NULL, -- ENDEREÇO DO DIRETÓRIO COM AS IMAGENS
	`USUARIO` INT NOT NULL, -- USUÁRIO RESPONSÁVEL POR INSERIR (ALTERAR) O EVENTO
	`DATA` DATETIME NOT NULL, -- DATA E HORA DO SERVIDOR
	`STATUS` TINYINT(1) NOT NULL DEFAULT 1, -- INATIVO (0), ATIVO (1)
	PRIMARY KEY (`ID`),
	FOREIGN KEY (`USUARIO`) REFERENCES USUARIO(`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE IF NOT EXISTS FINANCA (
	`ID` INT NOT NULL AUTO_INCREMENT, -- CHAVE ÚNICA ATRIBUÍDA À FINANÇA
	`PERIODO` VARCHAR(32) CHARACTER SET utf8 NOT NULL, -- PERÍODO (SEMANAL, MENSAL, BIMESTRAL, TRIMESTRAL, SEMESTRAL OU ANUAL) DA FINANÇA
	`ARQUIVO` VARCHAR(64) CHARACTER SET utf8 NOT NULL, -- ENDEREÇO DO ARQUIVO PDF
	`USUARIO` INT NOT NULL, -- USUÁRIO RESPONSÁVEL POR INSERIR (ALTERAR) A FINANÇA
	`DATA` DATETIME NOT NULL, -- DATA E HORA DO SERVIDOR
	`STATUS` TINYINT(1) NOT NULL DEFAULT 1, -- INATIVO (0), ATIVO (1)
	PRIMARY KEY (`ID`),
	FOREIGN KEY (`USUARIO`) REFERENCES USUARIO(`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE IF NOT EXISTS IMAGEM (
	`ID` INT NOT NULL AUTO_INCREMENT, -- CHAVE ÚNICA ATRIBUÍDA À IMAGEM
	`IMAGEM` VARCHAR(64) CHARACTER SET utf8 NOT NULL, -- NOME DA IMAGEM (JPG OU PNG)
	`EVENTO` INT NOT NULL, -- EVENTO AO QUAL A IMAGEM PERTENCE
	`STATUS` TINYINT(1) NOT NULL DEFAULT 1, -- INATIVO (0), ATIVO (1)
	PRIMARY KEY (`ID`),
	FOREIGN KEY (`EVENTO`) REFERENCES EVENTO(`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE IF NOT EXISTS JORNAL (
	`ID` INT NOT NULL AUTO_INCREMENT, -- CHAVE ÚNICA ATRIBUÍDA AO JORNAL
	`TITULO` VARCHAR(128) CHARACTER SET utf8 NOT NULL, -- TÍTULO DO JORNAL
	`EDICAO` INT NOT NULL UNIQUE, -- NÚMERO DA EDIÇÃO DO JORNAL
	`ARQUIVO` VARCHAR(64) CHARACTER SET utf8 NOT NULL, -- ENDEREÇO DO ARQUIVO PDF
	`IMAGEM` VARCHAR(64) CHARACTER SET utf8 NULL, -- ENDEREÇO DA IMAGEM (JPG OU PNG)
	`USUARIO` INT NOT NULL, -- USUÁRIO RESPONSÁVEL POR INSERIR (ALTERAR) O JORNAL
	`DATA` DATETIME NOT NULL, -- DATA E HORA DO SERVIDOR
	`STATUS` TINYINT(1) NOT NULL DEFAULT 1, -- INATIVO (0), ATIVO (1)
	PRIMARY KEY (`ID`),
	FOREIGN KEY (`USUARIO`) REFERENCES USUARIO(`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE IF NOT EXISTS JURIDICO (
	`ID` INT NOT NULL AUTO_INCREMENT, -- CHAVE ÚNICA ATRIBUÍDA AO JURÍDICO
	`TITULO` VARCHAR(128) CHARACTER SET utf8 NOT NULL, -- NOME DA PUBLICAÇÃO
	`DESCRICAO` TEXT CHARACTER SET utf8 NULL, -- DESCRIÇÃO DA PUBLICAÇÃO
	`ARQUIVO` VARCHAR(64) CHARACTER SET utf8 NOT NULL, -- ENDEREÇO DO ARQUIVO PDF
	`USUARIO` INT NOT NULL, -- USUÁRIO RESPONSÁVEL POR INSERIR (ALTERAR) O JURÍDICO
	`DATA` DATETIME NOT NULL, -- DATA E HORA DO SERVIDOR
	`STATUS` TINYINT(1) NOT NULL DEFAULT 1, -- INATIVO (0), ATIVO (1)
	PRIMARY KEY (`ID`),
	FOREIGN KEY (`USUARIO`) REFERENCES USUARIO(`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE IF NOT EXISTS NOTICIA (
	`ID` INT NOT NULL AUTO_INCREMENT, -- CHAVE ÚNICA ATRIBUÍDA À NOTÍCIA
	`TITULO` VARCHAR(128) CHARACTER SET utf8 NOT NULL, -- TÍTULO DA NOTÍCIA
	`SUBTITULO` TEXT CHARACTER SET utf8 NULL, -- SUBTÍTULO DA NOTÍCIA
	`TEXTO` TEXT CHARACTER SET utf8 NOT NULL, -- TEXTO DA NOTÍCIA
	`IMAGEM` VARCHAR(64) CHARACTER SET utf8 NULL, -- ENDEREÇO DA IMAGEM DE CABEÇALHO (JPG OU PNG)
	`USUARIO` INT NOT NULL, -- USUÁRIO RESPONSÁVEL POR INSERIR (ALTERAR) A NOTÍCIA
	`DATA` DATETIME NOT NULL, -- DATA E HORA DO SERVIDOR
	`STATUS` TINYINT(1) NOT NULL DEFAULT 1, -- INATIVO (0), ATIVO (1)
	PRIMARY KEY (`ID`),
	FOREIGN KEY (`USUARIO`) REFERENCES USUARIO(`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE IF NOT EXISTS PODCAST (
	`ID` INT NOT NULL AUTO_INCREMENT, -- CHAVE ÚNICA ATRIBUÍDA AO PODCAST
	`TITULO` VARCHAR(128) CHARACTER SET utf8 NOT NULL, -- TÍTULO DO PODCAST
	`AUDIO` VARCHAR(64) CHARACTER SET utf8 NOT NULL, -- ENDEREÇO DO ARQUIVO MP3
	`USUARIO` INT NOT NULL, -- USUÁRIO RESPONSÁVEL POR INSERIR (ALTERAR) O PODCAST
	`DATA` DATETIME NOT NULL, -- DATA E HORA DO SERVIDOR
	`STATUS` TINYINT(1) NOT NULL DEFAULT 1, -- INATIVO (0), ATIVO (1)
	PRIMARY KEY (`ID`),
	FOREIGN KEY (`USUARIO`) REFERENCES USUARIO(`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE IF NOT EXISTS REGISTRO (
	`ID` INT NOT NULL AUTO_INCREMENT, -- CHAVE ÚNICA ATRIBUÍDA AO REGISTRO
	`DESCRICAO` TEXT CHARACTER SET utf8 NOT NULL, -- DESCRIÇÃO DO REGISTRO
	`IP` VARCHAR(64) NOT NULL, -- ENDEREÇO LÓGICO DO USUÁRIO
	`DATA` DATETIME NOT NULL, -- DATA E HORA DO SERVIDOR
	PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;