CREATE DATABASE IF NOT EXISTS `SINTEEMAR` CHARACTER SET 'utf8' COLLATE 'utf8_general_ci';
USE `SINTEEMAR`;
SET COLLATION_CONNECTION = 'utf8_general_ci';
SET SQL_MODE = 'NO_AUTO_VALUE_ON_ZERO';

CREATE TABLE IF NOT EXISTS `BANNERS`(
	`ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`IMAGEM` VARCHAR(64) NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE IF NOT EXISTS `BOLETINS`(
	`ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`TITULO` VARCHAR(128) NOT NULL,
	`IMAGEM` VARCHAR(64) NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE IF NOT EXISTS `CONVENCOES`(
	`ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`TITULO` VARCHAR(128) NOT NULL,
	`TIPO` TINYINT(1) NOT NULL DEFAULT 1,
	`DOCUMENTO` VARCHAR(64) NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE IF NOT EXISTS `CONVENIOS`(
	`ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`TITULO` VARCHAR(128) NOT NULL,
	`TEXTO` TEXT NOT NULL,
	`TELEFONE` VARCHAR(16) NULL,
	`CELULAR` VARCHAR(16) NULL,
	`EMAIL` VARCHAR(64) NULL,
	`IMAGEM` VARCHAR(64) NOT NULL,
	`DOCUMENTO` VARCHAR(64) NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE IF NOT EXISTS `DIRETORIA`(
	`ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`TITULO` VARCHAR(128) NOT NULL,
	`IMAGEM` VARCHAR(64) NULL,
	`TEXTO` TEXT NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE IF NOT EXISTS `EDITAIS`(
	`ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`TITULO` VARCHAR(128) NOT NULL,
	`IMAGEM` VARCHAR(64) NOT NULL,
	`TEXTO` TEXT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE IF NOT EXISTS `ESTATUTO`(
	`ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`DOCUMENTO` VARCHAR(64) NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE IF NOT EXISTS `EVENTOS`(
	`ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`TITULO` VARCHAR(128) NOT NULL,
	`TEXTO` TEXT NULL,
	`IMAGENS` VARCHAR(64) NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE IF NOT EXISTS `FINANCAS`(
	`ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`TITULO` VARCHAR(64) NOT NULL,
	`DOCUMENTO` VARCHAR(64) NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE IF NOT EXISTS `JORNAIS`(
	`ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`TITULO` VARCHAR(128) NOT NULL,
	`EDICAO` INT NOT NULL,
	`DOCUMENTO` VARCHAR(64) NOT NULL,
	`IMAGEM` VARCHAR(64) NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE IF NOT EXISTS `JURIDICOS`(
	`ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`TITULO` VARCHAR(128) NOT NULL,
	`TEXTO` TEXT NULL,
	`DOCUMENTO` VARCHAR(64) NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE IF NOT EXISTS `NOTICIAS`(
	`ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`TITULO` VARCHAR(128) NOT NULL,
	`TEXTO` TEXT NOT NULL,
	`IMAGEM` VARCHAR(64) NULL,
	`DATA` DATE NOT NULL,
	`HORA` TIME NOT NULL,
	`STATUS` TINYINT(1) NOT NULL DEFAULT 1
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE IF NOT EXISTS `USUARIOS`(
	`ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`NOME` VARCHAR(64) NOT NULL,
	`EMAIL` VARCHAR(64) NOT NULL UNIQUE,
	`SENHA` VARCHAR(32) NOT NULL,
	`BANNERS` TINYINT(1) NOT NULL DEFAULT 0,
	`BOLETINS` TINYINT(1) NOT NULL DEFAULT 0,
	`CONVENCOES` TINYINT(1) NOT NULL DEFAULT 0,
	`CONVENIOS` TINYINT(1) NOT NULL DEFAULT 0,
	`DIRETORIA` TINYINT(1) NOT NULL DEFAULT 0,
	`EDITAIS` TINYINT(1) NOT NULL DEFAULT 0,
	`ESTATUTO` TINYINT(1) NOT NULL DEFAULT 0,
	`EVENTOS` TINYINT(1) NOT NULL DEFAULT 0,
	`FINANCAS` TINYINT(1) NOT NULL DEFAULT 0,
	`HISTORICO` TINYINT(1) NOT NULL DEFAULT 0,
	`JORNAIS` TINYINT(1) NOT NULL DEFAULT 0,
	`JURIDICOS` TINYINT(1) NOT NULL DEFAULT 0,
	`NOTICIAS` TINYINT(1) NOT NULL DEFAULT 0,
	`USUARIOS` TINYINT(1) NOT NULL DEFAULT 0,
	`VIDEOS` TINYINT(1) NOT NULL DEFAULT 0
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE IF NOT EXISTS `VIDEOS`(
	`ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`TITULO` VARCHAR(128) NOT NULL,
	`URL` VARCHAR(128) NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;