CREATE DATABASE IF NOT EXISTS `SINTEEMAR` CHARACTER SET 'utf8' COLLATE 'utf8_general_ci';
USE `SINTEEMAR`;
SET COLLATION_CONNECTION = 'utf8_general_ci';
SET SQL_MODE = 'NO_AUTO_VALUE_ON_ZERO';
SET time_zone = '-3:00';

CREATE TABLE IF NOT EXISTS `ARQUIVOS` (
	`ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`ARQUIVO` VARCHAR(64) NOT NULL,
	`OBSERVACAO` VARCHAR(64) NULL,
	`TEMPO` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE IF NOT EXISTS `AVISOS` (
	`ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`TITULO` VARCHAR(128) NOT NULL,
	`TEXTO` TEXT NOT NULL,
	`INICIO` DATE NOT NULL DEFAULT CURRENT_DATE,
	`FIM` DATE NOT NULL DEFAULT CURRENT_DATE,
	`TEMPO` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE IF NOT EXISTS `BANNERS` (
	`ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`IMAGEM` VARCHAR(64) NOT NULL,
	`LINK` VARCHAR(128) NULL,
	`TEMPO` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE IF NOT EXISTS `BOLETINS` (
	`ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`TITULO` VARCHAR(128) NOT NULL,
	`IMAGEM` VARCHAR(64) NOT NULL,
	`TEMPO` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE IF NOT EXISTS `CONVENCOES` (
	`ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`TITULO` VARCHAR(128) NOT NULL,
	`TIPO` TINYINT(1) NOT NULL DEFAULT 1,
	`DOCUMENTO` VARCHAR(64) NOT NULL,
	`TEMPO` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE IF NOT EXISTS `CONVENIOS` (
	`ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`TITULO` VARCHAR(128) NOT NULL,
	`TEXTO` TEXT NOT NULL,
	`TELEFONE` VARCHAR(16) NULL,
	`CELULAR` VARCHAR(16) NULL,
	`EMAIL` VARCHAR(64) NULL,
	`URL` VARCHAR(128) NULL,
	`IMAGEM` VARCHAR(64) NOT NULL,
	`DOCUMENTO` VARCHAR(64) NULL,
	`TEMPO` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE IF NOT EXISTS `DIRETORIA` (
	`ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`TITULO` VARCHAR(128) NOT NULL,
	`IMAGEM` VARCHAR(64) NULL,
	`TEXTO` TEXT NOT NULL,
	`TEMPO` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE IF NOT EXISTS `EDITAIS` (
	`ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`TITULO` VARCHAR(128) NOT NULL,
	`IMAGEM` VARCHAR(64) NOT NULL,
	`TEXTO` TEXT NULL,
	`TEMPO` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE IF NOT EXISTS `ESTATUTO` (
	`ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`DOCUMENTO` VARCHAR(64) NOT NULL,
	`TEMPO` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE IF NOT EXISTS `EVENTOS` (
	`ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`TITULO` VARCHAR(128) NOT NULL,
	`TEXTO` TEXT NULL,
	`IMAGENS` VARCHAR(64) NOT NULL,
	`TEMPO` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE IF NOT EXISTS `FINANCAS` (
	`ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`TITULO` VARCHAR(64) NOT NULL,
	`DOCUMENTO` VARCHAR(64) NOT NULL,
	`TEMPO` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE IF NOT EXISTS `JORNAIS` (
	`ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`TITULO` VARCHAR(128) NOT NULL,
	`EDICAO` INT NOT NULL,
	`DOCUMENTO` VARCHAR(64) NOT NULL,
	`IMAGEM` VARCHAR(64) NULL,
	`TEMPO` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE IF NOT EXISTS `JURIDICOS` (
	`ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`TITULO` VARCHAR(128) NOT NULL,
	`TEXTO` TEXT NULL,
	`DOCUMENTO` VARCHAR(64) NOT NULL,
	`TEMPO` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE IF NOT EXISTS `NOTICIAS` (
	`ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`TITULO` VARCHAR(128) NOT NULL,
	`TEXTO` TEXT NOT NULL,
	`IMAGEM` VARCHAR(64) NULL,
	`DATA` DATE NOT NULL DEFAULT CURRENT_DATE,
	`HORA` TIME NOT NULL DEFAULT CURRENT_TIME,
	`STATUS` TINYINT(1) NOT NULL DEFAULT 1,
	`TEMPO` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE IF NOT EXISTS `PODCASTS` (
	`ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`TITULO` VARCHAR(128) NOT NULL,
	`AUDIO` VARCHAR(64) NOT NULL,
	`DATA` DATE NOT NULL DEFAULT CURRENT_DATE,
	`HORA` TIME NOT NULL DEFAULT CURRENT_TIME,
	`TEMPO` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE IF NOT EXISTS `REGISTROS` (
	`ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`OPERACAO` VARCHAR(16) NOT NULL,
	`TABELA` VARCHAR(16) NOT NULL,
	`ERRO` VARCHAR(512) NULL,
	`REGISTRO` INT NOT NULL,
	`USUARIO` INT NOT NULL,
	`DATA` DATETIME NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE IF NOT EXISTS `USUARIOS` (
	`ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`NOME` VARCHAR(64) NOT NULL,
	`EMAIL` VARCHAR(64) NOT NULL UNIQUE,
	`SENHA` VARCHAR(32) NOT NULL,
	`ARQUIVOS` TINYINT(1) NOT NULL DEFAULT 0,
	`BANNERS` TINYINT(1) NOT NULL DEFAULT 0,
	`BOLETINS` TINYINT(1) NOT NULL DEFAULT 0,
	`CONVENCOES` TINYINT(1) NOT NULL DEFAULT 0,
	`CONVENIOS` TINYINT(1) NOT NULL DEFAULT 0,
	`DIRETORIA` TINYINT(1) NOT NULL DEFAULT 0,
	`EDITAIS` TINYINT(1) NOT NULL DEFAULT 0,
	`ESTATUTO` TINYINT(1) NOT NULL DEFAULT 0,
	`EVENTOS` TINYINT(1) NOT NULL DEFAULT 0,
	`FINANCAS` TINYINT(1) NOT NULL DEFAULT 0,
	`HISTORICO` TINYINT(1) NOT NULL DEFAULT 0,
	`JORNAIS` TINYINT(1) NOT NULL DEFAULT 0,
	`JURIDICOS` TINYINT(1) NOT NULL DEFAULT 0,
	`NOTICIAS` TINYINT(1) NOT NULL DEFAULT 0,
	`PODCASTS` TINYINT(1) NOT NULL DEFAULT 0,
	`USUARIOS` TINYINT(1) NOT NULL DEFAULT 0,
	`VIDEOS` TINYINT(1) NOT NULL DEFAULT 0,
	`TEMPO` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE IF NOT EXISTS `VIDEOS` (
	`ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`TITULO` VARCHAR(128) NOT NULL,
	`URL` VARCHAR(128) NOT NULL,
	`TEMPO` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;